#!/usr/bin/env python3
# lompicheck.py — 把 `loment lompicheck` 注册到 PATH 上的安装器 (docs/217)
#
# 这条命令由**两半**组成，这一份只管把两半接起来：
#
#   引擎   loment/tools/lompicheck.lomt  —— 用 Loment 写的，编成 PE/ELF。它只读本地两棵树，
#          逐文件比内容。**它不会联网**，而且不该会：PE 运行时只实现 8 个 syscall，里面
#          没有 socket（`loment/tools/win_shim_data.lomt` 的导入表就是全部家当）。
#   薄壳   本文件 --install 生成的两个注册器 —— 先用 git 把发布口 `FujoJTOP/lompi`
#          的一份缓存 clone 更新好，再把两个根交给引擎。
#
# 注册走的是启动器里那条 "`loment foo` -> PATH 上的 `loment-foo`"（git 的模型，
# lompi SKILL §7.2）—— **不动 Loment 的源码**：没有登记表、没有源码改动，把文件放上
# PATH 就有、删掉就没。
#
#   python tools/lompicheck.py --install ~/.local/bin     # 装（两个文件）
#   loment lompicheck                                     # 用完
#
# 生成的两个注册器里**烘死了本仓的绝对路径**（与 `loment_dist` 往启动器里灌版本号同一种
# 做法）：本仓搬了地方就重跑一次 --install。`$LOMPICHECK_REPO` / `$LOMPICHECK_CACHE`
# 可以各自覆盖。
#
# 退出码: 0 = 装好了 / 2 = 用法错或目标不是目录

from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: `loment lompicheck` 去拿发布口那一侧的地址。与 `loment_publish.REPOS["lompi"]["repo"]`
#: 同源 —— `tools/lompicheck_test.py` 里有一条判据钉着这件事。
OUTLET_URL = "https://github.com/FujoJTOP/lompi"

_SHIM_SH = '''#!/bin/sh
# Generated by `python tools/lompicheck.py --install`. Do not edit -- re-run --install.
# `loment lompicheck` reaches this file through the launcher's loment-<name> lookup
# (git's model: `git foo` runs `git-foo`). Nothing in Loment knows this command exists.
#
# Two halves: this shell updates a cached clone of the publish outlet with git, then the
# Loment engine compares the two local trees. The engine cannot fetch anything itself --
# the PE runtime has no socket.
set -u

repo=${{LOMPICHECK_REPO:-{repo}}}
cache=${{LOMPICHECK_CACHE:-$HOME/.lompi/cache/lompi}}
url={url}

# On Windows the POSIX launcher links an ELF and cannot be exec'd from Git Bash; the .cmd
# one is the one that works there (Loment SKILL section 0).
loment=loment
if [ -n "${{WINDIR:-}}" ] && command -v loment.cmd >/dev/null 2>&1; then
    loment=loment.cmd
fi

exe=$repo/loment/build/lompicheck
if [ -f "$exe.exe" ] && [ ! -f "$exe" ]; then
    exe=$exe.exe
fi
if [ ! -f "$exe" ]; then
    echo "lompicheck: building the engine (first run)" 1>&2
    ( cd "$repo" && "$loment" build loment/tools/lompicheck.lomt -o loment/build/lompicheck ) 1>&2 || exit 2
    if [ -f "$exe.exe" ] && [ ! -f "$exe" ]; then
        exe=$exe.exe
    fi
    if [ ! -f "$exe" ]; then
        echo "lompicheck: no engine at $exe after building -- is `loment` on PATH?" 1>&2
        exit 2
    fi
fi

stale=fresh
if [ ! -d "$cache/.git" ]; then
    mkdir -p "$(dirname "$cache")"
    # core.autocrlf=false is REQUIRED, not fussiness: the outlet repo has no
    # .gitattributes, and the Windows default would turn every checkout into CRLF --
    # so every file would differ from the source byte for byte and this command would
    # report 170 differences for a perfectly healthy outlet.
    git clone --quiet --depth 1 -c core.autocrlf=false -c core.eol=lf "$url" "$cache" 1>&2 || {{
        echo "lompicheck: cannot fetch the outlet and there is no cached copy at $cache" 1>&2
        exit 2
    }}
else
    # An older cache may have been cloned with the default setting: set it, then reset,
    # so the working tree gets rewritten with LF.
    git -C "$cache" config core.autocrlf false
    git -C "$cache" config core.eol lf
    if ! git -C "$cache" fetch --quiet --depth 1 origin main 1>&2; then
        stale=stale
    elif ! git -C "$cache" reset --quiet --hard FETCH_HEAD 1>&2; then
        stale=stale
    fi
fi

exec "$exe" "$repo" "$cache" "$stale"
'''

_SHIM_CMD = r'''@echo off
rem Generated by `python tools\lompicheck.py --install`. Do not edit -- re-run --install.
rem `loment lompicheck` reaches this file through the launcher's loment-<name> lookup.
rem Two halves: this batch file updates a cached clone of the publish outlet with git,
rem then the Loment engine compares the two local trees (it cannot fetch: no socket on PE).
rem No parenthesised block below -- %ERRORLEVEL% inside one expands at parse time and would
rem read the PREVIOUS command's value (the trap the launcher's own comments record).
setlocal
set "repo={repo}"
if defined LOMPICHECK_REPO set "repo=%LOMPICHECK_REPO%"
set "cache=%LOMPICHECK_CACHE%"
if not defined cache set "cache=%USERPROFILE%\.lompi\cache\lompi"
set "url={url}"

set "exe=%repo%\loment\build\lompicheck.exe"
if exist "%exe%" goto have_engine
echo lompicheck: building the engine (first run) 1>&2
pushd "%repo%"
call loment build loment/tools/lompicheck.lomt -o loment/build/lompicheck
set "rc=%ERRORLEVEL%"
popd
if not "%rc%"=="0" exit /b 2
if not exist "%exe%" exit /b 2

:have_engine
set "stale=fresh"
if exist "%cache%\.git" goto refresh
if not exist "%USERPROFILE%\.lompi" mkdir "%USERPROFILE%\.lompi"
if not exist "%USERPROFILE%\.lompi\cache" mkdir "%USERPROFILE%\.lompi\cache"
rem core.autocrlf=false is required, not fussiness: the outlet repo has no .gitattributes,
rem and the Windows default would turn every file into CRLF and report 170 differences.
git clone --quiet --depth 1 -c core.autocrlf=false -c core.eol=lf "%url%" "%cache%"
if errorlevel 1 goto no_cache
goto run

:refresh
git -C "%cache%" config core.autocrlf false
git -C "%cache%" config core.eol lf
git -C "%cache%" fetch --quiet --depth 1 origin main
if errorlevel 1 set "stale=stale"
git -C "%cache%" reset --quiet --hard FETCH_HEAD
if errorlevel 1 set "stale=stale"
goto run

:no_cache
echo lompicheck: cannot fetch the outlet and there is no cached copy at "%cache%" 1>&2
exit /b 2

:run
"%exe%" "%repo%" "%cache%" "%stale%"
exit /b %ERRORLEVEL%
'''


def cmd_install(directory: Path) -> int:
    if not directory.is_dir():
        print(f"lompicheck: not a directory: {directory}", file=sys.stderr)
        return 2
    repo = ROOT.as_posix()
    posix = directory / "loment-lompicheck"
    batch = directory / "loment-lompicheck.cmd"
    # **两份都写**: cmd 只认 .cmd, 而 Git Bash 的 `command -v loment-lompicheck` 只认
    # 无扩展名那份 —— 少任何一份, 就有一个 shell 里 `loment lompicheck` 是"未知命令"。
    posix.write_text(_SHIM_SH.format(repo=shlex.quote(repo), url=OUTLET_URL),
                     encoding="utf-8", newline="\n")
    posix.chmod(posix.stat().st_mode | 0o755)
    # CRLF 显式写: .cmd 是给 cmd.exe 按行解析的 (loment_dist 对包里的启动器也这样)。
    batch.write_text(_SHIM_CMD.format(repo=repo, url=OUTLET_URL),
                     encoding="ascii", newline="\r\n")
    print(f"lompicheck: registered `loment lompicheck` in {directory}")
    print(f"  {posix}")
    print(f"  {batch}")
    print(f"  engine: {ROOT / 'loment' / 'tools' / 'lompicheck.lomt'}")
    print("  (the repo path is baked in: if this checkout moves, run --install again)")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="lompicheck",
        description="Register `loment lompicheck` (the lompi publish-outlet check) on PATH. "
                    "The engine is a Loment program; the registrant is a shell wrapper "
                    "that refreshes a cached clone of the outlet with git.")
    ap.add_argument("--install", metavar="DIR",
                    help="write the two registrants (loment-lompicheck + .cmd) into DIR")
    a = ap.parse_args(argv)
    if not a.install:
        ap.print_help()
        return 2
    return cmd_install(Path(a.install).expanduser())


if __name__ == "__main__":
    sys.exit(main())
