#!/usr/bin/env python3
# lompicheck_test.py — `loment lompicheck` 的判据 (docs/222)
#
# 这条命令**自己就是一条注册出来的命令**（`docs/223` 形态 B）：单元里声明 `loment_command()`
# 与 `command_main`，产出因此叫 `loment-lompicheck`，放上 PATH 就有 `loment lompicheck`。
# 所以判据从"声明"一路判到"跑起来"，中间没有一段是靠读代码相信的：
#
#   1. **声明**（离线）—— 单元声明了这条命令、**没有** `_start`；库地址与发布清单同源。
#   2. **参考实现答得出名字** —— `--print-command` 答 `lompicheck`（构建前端就靠它命名）。
#   3. **编出来、跑起来**（要链）—— `--help` / `--refresh` / **真比一遍**：造一个临时发布口，
#      比一致、改一个文件再比出差异。**只断言"文件都在"是这套东西最容易骗过自己的地方。**
#   4. **默认路径从 `argv[0]` 推** —— 把产物放进一个带 `Users\<名>\` 的路径里跑，
#      它该把缓存推成 `<家目录>/.lompi/cache/lompi`（PE 上没有 getenv，这是唯一的定位方式）。
#
# 运行: python tools/lompicheck_test.py   (退出码 0 = 全绿)

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lomelf  # noqa: E402
import loment_publish  # noqa: E402
import lomentc  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "loment" / "tools" / "lompicheck.lomt"
IS_WIN = sys.platform == "win32"
TESTS: list[tuple[str, object]] = []


def test(fn):
    TESTS.append((fn.__name__, fn))
    return fn


_built: Path | None = None


def _build() -> Path:
    """把这条命令编成本机原生程序（与 `loment_register_test` 同一条路：参考编译器 + lomelf）。"""
    global _built
    if _built is not None:
        return _built
    mod, deps = lomentc.load_unit(SRC, ROOT)
    errs = lomentc.check(mod, deps=deps)
    assert not errs, f"命令自己检查不过: {errs[:3]}"
    ll = lomentc.emit_llvm(mod, ROOT, deps)
    raw = (lomelf.compile_pe if IS_WIN else lomelf.compile_ll)(ll)[0]
    assert raw, "链接器产出为空"
    td = Path(tempfile.mkdtemp(prefix="lompicheck-"))
    exe = td / ("loment-lompicheck.exe" if IS_WIN else "loment-lompicheck")
    exe.write_bytes(raw)
    exe.chmod(0o755)
    _built = exe
    return exe


def _make_outlet(td: Path) -> Path:
    """造一个"发布口"目录：`lompi/` 摊平到根 + `.claude/skills/lompi/` 原地 + 生成的 README。

    内容**拷自本仓真的那两棵树** —— 手写夹具测的是一个不会发生的输入。
    """
    out = td / "outlet"
    out.mkdir()
    for p in (ROOT / "lompi").iterdir():
        if p.is_dir():
            shutil.copytree(p, out / p.name)
        else:
            shutil.copy2(p, out / p.name)
    dst = out / ".claude" / "skills" / "lompi"
    dst.parent.mkdir(parents=True)
    shutil.copytree(ROOT / ".claude" / "skills" / "lompi", dst)
    (out / "README.md").write_text("# generated by loment_publish\n", encoding="utf-8")
    return out


def _run(*args: str, cwd: Path | None = None) -> tuple[int, str, str]:
    exe = _build()
    r = subprocess.run([str(exe), *args], cwd=str(cwd or ROOT), capture_output=True, text=True,
                       encoding="utf-8", errors="replace", shell=False, timeout=300)
    return r.returncode, r.stdout, r.stderr


# ---------------------------------------------------------------- 1. 声明

@test
def test_the_unit_declares_the_command_and_has_no_start():
    """它就是一条**注册出来的**命令：声明在源码里，`_start` 由工具链生成。

    自己写 `_start` 的话这条命令照样能跑 —— 但那就退回了"手抄入口"，而这正是
    `docs/223` 要消灭的东西。判据把这条钉住，免得哪天被"顺手写回去"。
    """
    src = SRC.read_text(encoding="utf-8")
    assert 'pub fn loment_command() -> str { return "lompicheck"; }' in src, "没有命令声明"
    assert "fn _start" not in src, "自己写了 `_start` —— 入口该由工具链生成"
    mod, deps = lomentc.load_unit(SRC, ROOT)
    assert mod.command == "lompicheck", f"参考实现读出来的名字是 {mod.command!r}"


@test
def test_outlet_url_matches_the_publish_list():
    """发布口地址写死在源码里（这个程序引不了 Python 的发布清单），所以钉一条判据。"""
    want = "https://github.com/" + loment_publish.REPOS["lompi"]["repo"]
    assert want in SRC.read_text(encoding="utf-8"), (
        f"命令里的发布口地址与 `loment_publish` 不一致（该是 {want}）—— 两处一起改")


@test
def test_print_command_answers_the_name():
    r = subprocess.run([sys.executable, str(ROOT / "tools" / "lomentc.py"), "--print-command",
                        str(SRC)], capture_output=True, text=True, encoding="utf-8",
                       errors="replace", shell=False, timeout=300)
    assert r.returncode == 0, r.stderr[-200:]
    assert r.stdout.strip() == "lompicheck", f"答的是 {r.stdout!r}"


# ---------------------------------------------------------------- 2. 跑起来

@test
def test_help_and_refresh():
    """`--help` 说清用法；`--refresh` **打出**更新缓存的那条 git 命令。

    这条命令联不了网（PE 运行时没有 socket），"怎么更新缓存"因此只能靠**打出来** ——
    与 `lompi fetch` 对同一个局面用的是同一招。判据钉住"打出来了、里面有两样东西"：
    发布口地址、和它自己推出来的缓存路径。
    """
    rc, out, _ = _run("--help")
    assert rc == 0, f"--help 退出 {rc}"
    assert "--source" in out and "--outlet" in out and "--refresh" in out, out

    rc, out, _ = _run("--refresh")
    assert rc == 0, f"--refresh 退出 {rc}"
    assert "git clone" in out and "git -C" in out, out
    assert "https://github.com/FujoJTOP/lompi" in out, out
    assert ".lompi/cache/lompi" in out, out


@test
def test_unknown_option_is_refused():
    rc, _out, err = _run("--nope")
    assert rc == 2, f"不认识的开关该退出 2，实际 {rc}"
    assert "unknown option" in err, err


@test
def test_the_real_comparison_reports_both_ways():
    """**真比一遍**：造一个发布口 -> 一致；改一个文件 -> 差异。

    一条只会说"一致"的命令与一条只会说"不一致"的命令都等于没有 —— 两个方向各判一次。
    """
    with tempfile.TemporaryDirectory() as tds:
        td = Path(tds)
        outlet = _make_outlet(td)
        rc, out, err = _run("--source", str(ROOT), "--outlet", str(outlet))
        assert rc == 0, f"造出来的发布口应当一致: rc={rc}\n{out}\n{err[-300:]}"
        assert "[OK]" in out and "identical" in out, out

        victim = outlet / "lpi_cli.lomt"
        victim.write_bytes(victim.read_bytes() + b"\n// edited\n")
        rc, out, _ = _run("--source", str(ROOT), "--outlet", str(outlet))
        assert rc == 1, f"内容不同应当退出 1: rc={rc}\n{out}"
        assert "differs  lpi_cli.lomt" in out, out

        # 目录不存在 -> 说清楚 + 非零，而不是"看起来比过了"
        rc, _out, err = _run("--source", str(ROOT), "--outlet", str(td / "nope"))
        assert rc == 2, f"发布口不存在该退出 2，实际 {rc}"
        assert "cannot read" in err.lower() or "cannot" in err.lower(), err


@test
def test_default_outlet_comes_from_argv0():
    """默认路径**从 `argv[0]` 推** —— PE 上没有 `getenv`，这是唯一定位得了的东西。

    做法：把产物拷进一个带 `Users/<名>/` 的路径里再跑，看它把缓存推成哪儿。
    （推不出来时它必须**说出来**让你用 `--outlet` 指明，而不是默默比一个空目录。）
    """
    exe = _build()
    with tempfile.TemporaryDirectory() as tds:
        td = Path(tds)
        fake = td / "Users" / "tester" / "bin"
        fake.mkdir(parents=True)
        copy = fake / exe.name
        shutil.copyfile(exe, copy)
        copy.chmod(0o755)
        r = subprocess.run([str(copy), "--refresh"], capture_output=True, text=True,
                           encoding="utf-8", errors="replace", shell=False, timeout=300)
        assert r.returncode == 0, r.stderr[-200:]
        # 期望值**照规则算**：家目录 = argv[0] 里**第一段** `Users/<名>` 之前的那一截。
        # 不能直接拿 `td` 当期望 —— 本机的临时目录自己就住在一个 Users 家目录底下，
        # 那样写会先命中别的地方，测出来的是临时目录住在哪，不是这条规矩。
        q = copy.as_posix()
        marks = [i for i in (q.find("/Users/"), q.find("/home/")) if i >= 0]
        assert marks, "夹具路径里没有家目录标记，这条判据测不了"
        m = min(marks)
        mlen = 7 if m == q.find("/Users/") else 6
        end = q.find("/", m + mlen)          # 家目录到**名字后面那个**分隔符为止
        assert end > m, "夹具路径不完整，这条判据测不了"
        want = q[:end] + "/.lompi/cache/lompi"
        assert want in r.stdout.replace(chr(92), "/"), (
            "没从 argv[0] 推出缓存路径。期望里面有 " + want + "，实际:" + chr(10) + r.stdout)


def main() -> int:
    failed = []
    for name, fn in TESTS:
        try:
            fn()
            print(f"  PASS  {name}")
        except Exception as e:  # noqa: BLE001
            failed.append((name, e))
            print(f"  FAIL  {name}: {type(e).__name__}: {e}")
    print(f"\nlompicheck_test: {len(TESTS) - len(failed)}/{len(TESTS)} 通过")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
